# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/final_project_grade_3/final_project_grade_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_project_grade_3 || ORIG_REF_NAME==final_project_grade_3} -quiet] -quiet

# IP: bd/final_project_grade_3/ip/final_project_grade_3_processing_system7_0_0/final_project_grade_3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_project_grade_3_processing_system7_0_0 || ORIG_REF_NAME==final_project_grade_3_processing_system7_0_0} -quiet] -quiet

# XDC: bd/final_project_grade_3/final_project_grade_3_ooc.xdc
