# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deazon/final_project/final_project.srcs/sources_1/bd/final_project_grade_3/ip/final_project_grade_3_processing_system7_0_0/final_project_grade_3_processing_system7_0_0.xci
# IP: The module: 'final_project_grade_3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deazon/final_project/final_project.srcs/sources_1/bd/final_project_grade_3/ip/final_project_grade_3_processing_system7_0_0/final_project_grade_3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_project_grade_3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/deazon/final_project/final_project.srcs/sources_1/bd/final_project_grade_3/ip/final_project_grade_3_processing_system7_0_0/final_project_grade_3_processing_system7_0_0.xci
# IP: The module: 'final_project_grade_3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deazon/final_project/final_project.srcs/sources_1/bd/final_project_grade_3/ip/final_project_grade_3_processing_system7_0_0/final_project_grade_3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_project_grade_3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
